version: '3'

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    volumes:
      - .:/source/
    working_dir: /source/
    command: bash -c "
      gunicorn -w $APP_WORKER
      -b $APP_HOST:$APP_PORT
      wsgi:app
      "
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:latest
    env_file:
      - .env
    restart: always
