version: '3'

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    volumes:
      - .:/source/
    working_dir: /source/
    command: gunicorn --bind 0.0.0.0:8080 wsgi:app

    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:latest
    env_file:
      - .env
    restart: always
